server:
  port: 8002


spring:
  application:
    name: cloud-consumer-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3366/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456