server:
  port: 8002

spring:
  application:
    name: cloud-payment-service #与8001的服务名相同
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3366/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.atguigu.springcloud.entity #所有entity别名实体类所在包
  mapper-locations: classpath:mapper/*.xml #mapper文件位置

eureka:
  client:
    register-with-eureka: true   #将自己注册到eureka
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #eureka服务地址
      #defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8002 #在eureka中显示的名字，防止出现与本机有关的信息
    prefer-ip-address: true #点击访问路径可以显示ip地址
